export const AGENTS = [
  { id: 'planner', label: 'Planner' },
  { id: 'explorer', label: 'Explorer' },
  { id: 'evidence_analyst', label: 'Evidence Analyst' },
  { id: 'critic', label: 'Critic' },
  { id: 'synthesizer', label: 'Synthesizer' },
]

export const REPORT_SECTIONS = [
  { id: 'summary', title: 'Research Summary', agent: 'synthesizer' },
  { id: 'findings', title: 'Key Findings', agent: 'evidence_analyst' },
  { id: 'gaps', title: 'Research Gap Analysis', agent: 'critic' },
  { id: 'contradictions', title: 'Contradictions', agent: 'critic' },
  { id: 'confidence', title: 'Confidence Score', agent: 'critic' },
  { id: 'references', title: 'References', agent: 'synthesizer' },
]

export const EVIDENCE_INSPECTOR_SECTIONS = [
  { id: 'literature', title: 'Supporting Literature' },
  { id: 'integrity', title: 'Research Integrity' },
  { id: 'exact-evidence', title: 'Exact Evidence' },
  { id: 'methodology', title: 'Methodology Review' },
  { id: 'metadata', title: 'Paper Metadata' },
  { id: 'reproducibility', title: 'Reproducibility' },
]

export const GRAPH_NODE_STYLES = {
  Paper: { fill: '#0f172a', shape: 'rounded', strokeDash: null },
  Concept: { fill: '#4f7cff', shape: 'circle', strokeDash: null },
  Topic: { fill: '#5b86ff', shape: 'circle', strokeDash: null },
  Method: { fill: '#3b63d9', shape: 'rounded', strokeDash: null },
  Algorithm: { fill: '#64748b', shape: 'diamond', strokeDash: null },
  Dataset: { fill: '#6b7fad', shape: 'hex', strokeDash: null },
  Author: { fill: '#7c8db5', shape: 'circle', strokeDash: '2 2' },
  Venue: { fill: '#94a3b8', shape: 'hex', strokeDash: null },
  'Research Gap': { fill: '#94a3b8', shape: 'triangle', strokeDash: '3 2' },
}

export const GRAPH_EDGE_STYLES = {
  AUTHOR_OF: 'solid',
  HAS_CONCEPT: 'dashed',
  HAS_KEYWORD: 'dashed',
  PUBLISHED_IN: 'dotted',
  CITES: 'solid',
  RELATED_TO: 'dotted',
  enables: 'solid',
  'orchestrated by': 'solid',
  executes: 'solid',
  grounds: 'solid',
  'supported by': 'dashed',
  'evaluated by': 'dashed',
  'retrieves from': 'dotted',
  'provides graph for': 'dotted',
}

export const SESSION_STATUSES = Object.freeze({
  DRAFT: 'draft',
  RUNNING: 'running',
  COMPLETED: 'completed',
  FAILED: 'failed',
})

/**
 * Seed metadata for Research Sessions drawer.
 * Full workspace snapshots are attached at runtime in Home.
 */
export const RESEARCH_SESSIONS_SEED = [
  {
    id: 'session-1',
    title: 'GraphRAG Explainability',
    query: 'How do GraphRAG systems improve explainability?',
    status: SESSION_STATUSES.COMPLETED,
    pinned: true,
    archived: false,
    filters: {
      yearFrom: '2020',
      yearTo: '2025',
      domain: 'Computer Science',
      publicationType: '',
      minCitations: '50',
      openAccess: true,
    },
    sortBy: 'relevant',
    graphMode: 'concept',
    selectedPaperId: 'paper-graphrag-survey',
    selectedConceptId: 'c1',
    uploadedSources: [{ name: 'graphrag-notes.pdf', size: 240112 }],
  },
  {
    id: 'session-2',
    title: 'Sleep & Memory Review',
    query: 'Evidence linking sleep quality to memory consolidation',
    status: SESSION_STATUSES.COMPLETED,
    pinned: false,
    archived: false,
    filters: {
      yearFrom: '2018',
      yearTo: '2024',
      domain: 'Neuroscience',
      publicationType: 'Journal Article',
      minCitations: '',
      openAccess: false,
    },
    sortBy: 'cited',
    graphMode: 'citation',
    selectedPaperId: 'paper-rag-foundations',
    selectedConceptId: null,
    uploadedSources: [{ name: 'sleep-corpus.txt', size: 18432 }],
  },
  {
    id: 'session-3',
    title: 'Transformer Citation Survey',
    query: 'Citation patterns in transformer architecture surveys',
    status: SESSION_STATUSES.DRAFT,
    pinned: false,
    archived: false,
    filters: {
      yearFrom: '2017',
      yearTo: '2025',
      domain: 'Computer Science',
      publicationType: 'Review',
      minCitations: '100',
      openAccess: true,
    },
    sortBy: 'newest',
    graphMode: 'concept',
    selectedPaperId: null,
    selectedConceptId: null,
    uploadedSources: [],
  },
  {
    id: 'session-4',
    title: 'Clinical XAI Draft',
    query: 'Explainable AI in clinical decision support',
    status: SESSION_STATUSES.FAILED,
    pinned: false,
    archived: false,
    filters: {
      yearFrom: '2019',
      yearTo: '2025',
      domain: 'Medicine',
      publicationType: '',
      minCitations: '',
      openAccess: true,
    },
    sortBy: 'relevant',
    graphMode: 'concept',
    selectedPaperId: null,
    selectedConceptId: null,
    uploadedSources: [{ name: 'cds-protocol.docx', size: 51200 }],
  },
  {
    id: 'session-5',
    title: 'Healthcare GraphRAG Gap',
    query: 'GraphRAG for healthcare explainability',
    status: SESSION_STATUSES.RUNNING,
    pinned: false,
    archived: false,
    filters: {
      yearFrom: '2020',
      yearTo: '2025',
      domain: 'Medicine',
      publicationType: '',
      minCitations: '10',
      openAccess: true,
    },
    sortBy: 'relevant',
    graphMode: 'concept',
    selectedPaperId: null,
    selectedConceptId: 'c9',
    uploadedSources: [],
  },
]

/** @deprecated Use RESEARCH_SESSIONS_SEED */
export const RESEARCH_HISTORY_SEED = RESEARCH_SESSIONS_SEED

export const FINDING_CONCEPT_MAP = {
  0: ['c1', 'c3', 'c8'],
  1: ['c1', 'c4', 'c5', 'c6'],
  2: ['c2', 'c8'],
}

export const RESEARCH_DOMAINS = [
  'Computer Science',
  'Neuroscience',
  'Medicine',
  'Social Sciences',
  'Engineering',
]

export const PUBLICATION_TYPES = [
  'Journal Article',
  'Conference Paper',
  'Preprint',
  'Review',
  'Thesis',
]

export const SORT_OPTIONS = [
  { id: 'relevant', label: 'Most Relevant' },
  { id: 'cited', label: 'Most Cited' },
  { id: 'newest', label: 'Newest' },
]

export const ACCEPTED_UPLOAD_TYPES = {
  'application/pdf': 'PDF',
}

export const RECENT_SEARCHES = [
  'How do GraphRAG systems improve explainability?',
  'Evidence linking sleep quality to memory consolidation',
  'Citation patterns in transformer architecture surveys',
]

export const CONCEPT_GRAPH = {
  kind: 'concept',
  nodes: [
    {
      id: 'c1',
      label: 'GraphRAG',
      type: 'Concept',
      importance: 'primary',
      x: 260,
      y: 190,
      description: 'Retrieval-augmented generation grounded in graph-structured knowledge.',
      relatedPaperIds: ['paper-graphrag-survey', 'paper-rag-foundations'],
    },
    {
      id: 'c2',
      label: 'Explainability',
      type: 'Topic',
      importance: 'major',
      x: 420,
      y: 90,
      description: 'Methods that make model evidence, decisions, and provenance inspectable.',
      relatedPaperIds: ['paper-graphrag-survey'],
    },
    {
      id: 'c8',
      label: 'Evidence Paths',
      type: 'Concept',
      importance: 'minor',
      x: 520,
      y: 160,
      description: 'Traceable routes from generated claims back to supporting literature.',
      relatedPaperIds: ['paper-graphrag-survey', 'paper-openalex'],
    },
    {
      id: 'c7',
      label: 'Researcher',
      type: 'Author',
      importance: 'minor',
      x: 340,
      y: 30,
      description: 'The human evaluator who inspects, validates, and curates research evidence.',
      relatedPaperIds: ['paper-openalex'],
    },
    {
      id: 'c3',
      label: 'Multi-Agent',
      type: 'Method',
      importance: 'major',
      x: 90,
      y: 230,
      description: 'Specialized agents coordinate planning, exploration, critique, and synthesis.',
      relatedPaperIds: ['paper-graphrag-survey'],
    },
    {
      id: 'c6',
      label: 'Citation Traversal',
      type: 'Algorithm',
      importance: 'minor',
      x: 140,
      y: 340,
      description: 'Graph traversal over citation links to discover connected evidence.',
      relatedPaperIds: ['paper-openalex', 'paper-rag-foundations'],
    },
    {
      id: 'c4',
      label: 'OpenAlex',
      type: 'Dataset',
      importance: 'major',
      x: 400,
      y: 300,
      description: 'An open scholarly graph of works, authors, venues, institutions, and concepts.',
      relatedPaperIds: ['paper-openalex'],
    },
    {
      id: 'c5',
      label: 'Semantic Scholar',
      type: 'Dataset',
      importance: 'major',
      x: 530,
      y: 260,
      description: 'A scholarly metadata source for papers, citations, authors, and abstracts.',
      relatedPaperIds: ['paper-graphrag-survey', 'paper-openalex'],
    },
    {
      id: 'c9',
      label: 'Healthcare Gap',
      type: 'Research Gap',
      importance: 'minor',
      x: 580,
      y: 70,
      description: 'Limited research on GraphRAG for healthcare explainability.',
      relatedPaperIds: ['paper-graphrag-survey'],
    },
  ],
  links: [
    {
      id: 'e1',
      source: 'c1',
      target: 'c2',
      type: 'enables',
      explanation: 'GraphRAG improves explainability by preserving graph-based evidence provenance.',
      supportingPaperIds: ['paper-graphrag-survey'],
      confidence: 94,
    },
    {
      id: 'e2',
      source: 'c1',
      target: 'c3',
      type: 'orchestrated by',
      explanation: 'Multi-agent workflows separate GraphRAG planning, exploration, critique, and synthesis.',
      supportingPaperIds: ['paper-graphrag-survey'],
      confidence: 91,
    },
    {
      id: 'e3',
      source: 'c1',
      target: 'c4',
      type: 'retrieves from',
      explanation: 'GraphRAG uses OpenAlex metadata to construct connected scholarly evidence.',
      supportingPaperIds: ['paper-openalex', 'paper-graphrag-survey'],
      confidence: 89,
    },
    {
      id: 'e4',
      source: 'c1',
      target: 'c5',
      type: 'retrieves from',
      explanation: 'Semantic Scholar contributes citation and abstract metadata to GraphRAG retrieval.',
      supportingPaperIds: ['paper-graphrag-survey'],
      confidence: 88,
    },
    {
      id: 'e5',
      source: 'c2',
      target: 'c8',
      type: 'supported by',
      explanation: 'Evidence Paths improve explainability by tracing conclusions to supporting literature.',
      supportingPaperIds: ['paper-graphrag-survey'],
      confidence: 96,
    },
    {
      id: 'e6',
      source: 'c2',
      target: 'c7',
      type: 'evaluated by',
      explanation: 'Researchers inspect evidence provenance to assess explanation quality and trust.',
      supportingPaperIds: ['paper-openalex'],
      confidence: 82,
    },
    {
      id: 'e7',
      source: 'c3',
      target: 'c6',
      type: 'executes',
      explanation: 'Explorer agents perform citation traversal to retrieve related scholarly evidence.',
      supportingPaperIds: ['paper-graphrag-survey', 'paper-openalex'],
      confidence: 90,
    },
    {
      id: 'e8',
      source: 'c4',
      target: 'c6',
      type: 'provides graph for',
      explanation: 'OpenAlex citation relationships provide the graph traversed during evidence discovery.',
      supportingPaperIds: ['paper-openalex'],
      confidence: 93,
    },
    {
      id: 'e9',
      source: 'c8',
      target: 'c1',
      type: 'grounds',
      explanation: 'Evidence paths ground GraphRAG outputs in inspectable sources and exact claim locations.',
      supportingPaperIds: ['paper-graphrag-survey', 'paper-rag-foundations'],
      confidence: 95,
    },
    {
      id: 'e10',
      source: 'c2',
      target: 'c9',
      type: 'supported by',
      explanation: 'Explainability literature reveals a sparse evidence base for healthcare GraphRAG applications.',
      supportingPaperIds: ['paper-graphrag-survey'],
      confidence: 74,
    },
  ],
}

export const CITATION_EXPLORER_TREE = {
  id: 'paper-graphrag-survey',
  title: 'GraphRAG Survey (2025)',
  authors: ['Darren Edge', 'Ha Trinh', 'Newman Cheng'],
  year: 2025,
  venue: 'arXiv',
  citationCount: 486,
  badges: ['Open Access', 'Highly Cited', 'Survey Paper'],
  doi: '10.48550/arXiv.2404.16130',
  url: 'https://arxiv.org/abs/2404.16130',
  abstract:
    'A survey of graph-based retrieval-augmented generation methods, evidence traversal, and evaluation practices.',
  supportingPapers: 3,
  citedBy: 486,
  children: [
    {
      id: 'supporting-a',
      title: 'Supporting Paper A',
      authors: ['A. Researcher', 'B. Scholar'],
      year: 2024,
      venue: 'Journal of AI Research',
      citationCount: 124,
      badges: ['Open Access', 'Benchmark'],
      doi: '10.1000/supporting-a',
      url: 'https://openalex.org',
      abstract:
        'Examines graph-guided retrieval strategies for evidence-grounded synthesis.',
      supportingPapers: 2,
      citedBy: 124,
      children: [
        {
          id: 'supporting-a1',
          title: 'Supporting Paper A1',
          authors: ['C. Author'],
          year: 2023,
          venue: 'ACL',
          citationCount: 48,
          badges: ['Peer Reviewed', 'Experimental'],
          doi: '10.1000/supporting-a1',
          url: 'https://openalex.org',
          abstract: 'Evaluates entity-linking methods for scholarly knowledge graphs.',
          supportingPapers: 0,
          citedBy: 48,
        },
        {
          id: 'supporting-a2',
          title: 'Supporting Paper A2',
          authors: ['D. Author', 'E. Author'],
          year: 2022,
          venue: 'EMNLP',
          citationCount: 63,
          badges: ['Peer Reviewed', 'Benchmark'],
          doi: '10.1000/supporting-a2',
          url: 'https://openalex.org',
          abstract: 'Studies citation-aware retrieval across multidisciplinary corpora.',
          supportingPapers: 0,
          citedBy: 63,
        },
      ],
    },
    {
      id: 'supporting-b',
      title: 'Supporting Paper B',
      authors: ['F. Researcher'],
      year: 2023,
      venue: 'CHI',
      citationCount: 91,
      badges: ['Peer Reviewed', 'Open Access'],
      doi: '10.1000/supporting-b',
      url: 'https://openalex.org',
      abstract: 'Analyzes explainability interfaces for retrieval-augmented systems.',
      supportingPapers: 0,
      citedBy: 91,
    },
    {
      id: 'supporting-c',
      title: 'Supporting Paper C',
      authors: ['G. Scholar', 'H. Scholar'],
      year: 2021,
      venue: 'Information Processing & Management',
      citationCount: 205,
      badges: ['Highly Cited', 'Survey Paper'],
      doi: '10.1000/supporting-c',
      url: 'https://openalex.org',
      abstract: 'Introduces evidence provenance methods for research synthesis.',
      supportingPapers: 0,
      citedBy: 205,
    },
  ],
}

export const DEMO_REPORT = {
  summary:
    'GraphRAG systems improve research explainability by grounding answers in traversable citation graphs and explicit evidence paths rather than opaque retrieval rankings.',
  findings: [
    'Multi-agent pipelines separate planning, exploration, and critique into inspectable stages.',
    'Citation-aware retrieval surfaces bridging papers missed by keyword search.',
    'Confidence rises when contradictions are surfaced and adjudicated before synthesis.',
  ],
  supportingLiterature: [
    {
      id: 'paper-graphrag-survey',
      title: 'From Local to Global: A Graph RAG Approach to Query-Focused Summarization',
      authors: ['Darren Edge', 'Ha Trinh', 'Newman Cheng'],
      year: 2024,
      citationCount: 486,
      venue: 'arXiv',
      confidence: 94,
      url: 'https://arxiv.org/abs/2404.16130',
      doi: '10.48550/arXiv.2404.16130',
      abstract:
        'A graph-based retrieval approach that builds entity knowledge graphs and community summaries for global sensemaking over private datasets.',
      badges: ['Peer Reviewed', 'Open Access', 'Highly Cited', 'Benchmark'],
      reproducibility: {
        codeAvailable: true,
        datasetAvailable: true,
        githubRepository: 'microsoft/graphrag',
        papersWithCode: true,
      },
      evidenceLocation: {
        page: 12,
        section: '4.2',
        paragraph: 3,
        sentence: 'GraphRAG improved retrieval accuracy across global summarization tasks.',
      },
    },
    {
      id: 'paper-rag-foundations',
      title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
      authors: ['Patrick Lewis', 'Ethan Perez', 'Aleksandra Piktus'],
      year: 2020,
      citationCount: 8452,
      venue: 'NeurIPS',
      confidence: 91,
      url: 'https://arxiv.org/abs/2005.11401',
      doi: '10.48550/arXiv.2005.11401',
      abstract:
        'Introduces retrieval-augmented generation, combining parametric and non-parametric memory for knowledge-intensive language tasks.',
      badges: ['Peer Reviewed', 'Open Access', 'Highly Cited'],
      reproducibility: {
        codeAvailable: true,
        datasetAvailable: true,
        githubRepository: 'huggingface/transformers',
        papersWithCode: true,
      },
      evidenceLocation: {
        page: 5,
        section: '3.1',
        paragraph: 2,
        sentence: 'Retrieval augmentation improves factuality on knowledge-intensive generation tasks.',
      },
    },
    {
      id: 'paper-openalex',
      title: 'OpenAlex: A Fully-Open Index of Scholarly Works, Authors, Venues, Institutions, and Concepts',
      authors: ['Jason Priem', 'Heather Piwowar', 'Richard Orr'],
      year: 2022,
      citationCount: 1187,
      venue: 'arXiv',
      confidence: 87,
      url: 'https://arxiv.org/abs/2205.01833',
      doi: '10.48550/arXiv.2205.01833',
      abstract:
        'Describes OpenAlex, an open scholarly graph connecting works, authors, institutions, venues, and concepts.',
      badges: ['Open Access', 'Highly Cited', 'Survey Paper'],
      reproducibility: {
        codeAvailable: true,
        datasetAvailable: true,
        githubRepository: 'ourresearch/openalex-guts',
        papersWithCode: false,
      },
      evidenceLocation: {
        page: 8,
        section: '5',
        paragraph: 1,
        sentence: 'OpenAlex exposes scholarly entities and relationships as an open, connected metadata graph.',
      },
    },
  ],
  integrity: [
    { label: 'Peer Reviewed', value: '✓' },
    { label: 'Open Access', value: '✓' },
    { label: 'Retraction Status', value: 'None' },
    { label: 'Correction Status', value: 'None' },
    { label: 'Venue Quality', value: 'High' },
    { label: 'DOI', value: 'Available' },
  ],
  methodology: {
    strengths: [
      'Large, diverse scholarly dataset',
      'Multiple retrieval benchmarks',
      'Strong evaluation metrics',
    ],
    weaknesses: [
      'Limited external validation',
      'Evaluation concentrated in English-language literature',
      'Few longitudinal studies',
    ],
  },
  contradictions: [
    'Some GraphRAG variants prioritize recall over fidelity, reducing trust in generated claims.',
    'Explainability metrics remain inconsistently defined across recent literature.',
  ],
  researchGaps: {
    title: 'Potential Research Gap',
    summary: 'Very limited research exists on GraphRAG for Healthcare Explainability.',
    evidence: 'Only 3 directly relevant publications were identified.',
  },
  confidence: 86,
  references: [
    'Lewis et al. — Retrieval-Augmented Generation for Knowledge-Intensive NLP',
    'Edge et al. — From Local to Global: A Graph RAG Approach',
    'OpenAlex Documentation — Scholarly Metadata Graph',
  ],
}
